### ISSUE TITLE
[1.10] Putting Anvil pet in invent kicks users.

### ISSUE THREAD

**Issue by CNIAngel** [capnkirok/Inventory-Pets#112]
So I just installed this awesome mod onto a Minecraft server I play on and it's pretty interesting. The only issue we've had so far is that as soon as the Anvil pet is put into someone's inventory, they crash. 

I investigated the issue and the same thing happened to me and I've got the error right here.

```
[19:46:27] [Server thread/WARN]: Failed to handle packet for /XX.XX.XXX.XX:XXXXX
net.minecraft.util.ReportedException: Ticking player
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:380) ~[lu.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162) ~[me.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:212) ~[NetworkDispatcher$1.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) ~[eo.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
at com.inventorypets.petAnvil.func_77663_a(petAnvil.java:310) ~[petAnvil.class:?]
at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:437) ~[adz.class:?]
at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:344) ~[zr.class:?]
at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:510) ~[zs.class:?]
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2019) ~[sf.class:?]
at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233) ~[zs.class:?]
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303) ~[lu.class:?]
```

We're currently running 1.4.7.1 of the mod. I'll be updating it to 1.4.8.1 in a moment, but thought I should bring it up right now. (X'd out my IP for privacy reasons)

**Comment by capnkirok** [comment]
Hey Grant. Yes, this one was fixed in 1.4.8, so an upgrade to the latest will fix it. Thanks!
