### ISSUE TITLE
Stone Spawn Server Crash

### ISSUE THREAD

**Issue by HeartlessWind** [capnkirok/Inventory-Pets#147]
I am having an issue where when I go to open certain Inventory Pets spawned chests in the world my server crashes.  
The console gives me this error.

http://pastebin.com/xBFmd1aT

I've tried updating Inventory pets to the latest 1.7.10 version (1.4.9) but the issue is still occurring.

**Comment by capnkirok** [comment]
Haven't seen this in a while. This is caused by a block ticking on the edge of a chunk that is on the border of your world. I've put in error trapping but it may not be working for some reason.  The best way to handle it quickly is to destroy the block.... or expand the world.

The block is a StoneSpawn, which is found in the underground dungeon...

I will also look into it, but it will take some time.

**Comment by capnkirok** [comment]
I've put in an additional check here...  in the 1.4.9.4 release. Let me know if you are still receiving this.

**Comment by Yiyuiii** [comment]
Well, I encountered this issue today with the 1.12-2.0.15 release. I'd paste the crash log here:
```
java.lang.StackOverflowError: Exception ticking world
	at java.util.WeakHashMap.getTable(Unknown Source)
	at java.util.WeakHashMap.get(Unknown Source)
	at java.util.Collections$SynchronizedMap.get(Unknown Source)
	at net.minecraftforge.common.ForgeChunkManager.getPersistentChunksFor(ForgeChunkManager.java:895)
	at net.minecraft.world.World.getPersistentChunks(World.java:4286)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:672)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:660)
	at com.inventorypets.blocks.StoneSpawn.func_180650_b(StoneSpawn.java:89)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:680)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:660)
	at com.inventorypets.blocks.StoneSpawn.func_180650_b(StoneSpawn.java:89)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:680)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:660)
        ...(repeating)
```
The cause may be similar to those mentioned before.
