### ISSUE TITLE
[1.7.10] Rendering screen crash

### ISSUE THREAD

**Issue by enimog** [capnkirok/Inventory-Pets#148]
Hello ! Just to report this crash someone on my server got :

java.lang.ArrayIndexOutOfBoundsException: 500
	at com.inventorypets.petCustom.func_77624_a(petCustom.java:554)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:525)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:104)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:171)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by capnkirok** [comment]
Will check it out. Do you have a modlist?

**Comment by enimog** [comment]
Sure, see the attached picture:
![modlist](https://cloud.githubusercontent.com/assets/11507070/22988874/a79835b4-f381-11e6-9cd9-6e79a474f75b.PNG)

**Comment by capnkirok** [comment]
Cheers. I'll see what I can dig up!

**Comment by capnkirok** [comment]
Really sorry I didn't look at this one more closely earlier. The custom pet is no longer part of Inventory Pets, though the item remains as a legacy. The user should delete/remove this pet from their inventory entirely. Custom Pets was made into an entirely new mod. Sorry for late reply.
