### ISSUE TITLE
[1.11.2] Crash

### ISSUE THREAD

**Issue by allanf181** [capnkirok/Inventory-Pets#166]
```java
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TweaksLoadingPlugin (CCTweaks-1.11.2-1.3.3.jar)
  RebornCoreASM (RebornCore-1.11.2-2.14.0.81-universal.jar)
  BookshelfLoadingPlugin (Bookshelf-1.11.2-1.5.0.369.jar)
  NEICorePlugin (NotEnoughItems-1.11.2-2.2.0.217-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.11.2-2.6.0.254-universal.jar)
  UnborkedPlugin (unborked-1.11.2-1.80pr0-1.1.4.jar)
  LoadingPlugin (Quark-r1.2-90.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-75.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.2-beta4-anarchy.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.4.jar)
  CoreMod (Aroma1997Core-1.11.2-1.2.0.0.b81.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 4/24/17 11:41 PM
Description: Rendering screen

java.lang.ClassCastException: net.minecraft.item.ItemAir cannot be cast to com.inventorypets.petDoubleChest
	at com.inventorypets.GuiDoubleChestPet.func_146976_a(GuiDoubleChestPet.java:27)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:76)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:530)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1425)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.inventorypets.GuiDoubleChestPet.func_146976_a(GuiDoubleChestPet.java:27)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:76)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:530)

-- Screen render details --
Details:
	Screen name: com.inventorypets.GuiDoubleChestPet
	Mouse location: Scaled: (400, 209). Absolute: (800, 419)
	Screen size: Scaled: (800, 419). Absolute: (1600, 838). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['armelin1'/64189, l='MpServer', x=98.69, y=89.00, z=61.47]]
	Chunk stats: MultiplayerChunkCache: 273, 273
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,68,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 69461030 game time, 12835682 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 94 total; [EntitySkeletonHorse['Skeleton Horse'/0, l='MpServer', x=80.70, y=78.00, z=94.22], EntitySkeletonHorse['Skeleton Horse'/1, l='MpServer', x=82.17, y=78.00, z=94.30], EntitySkeletonHorse['Skeleton Horse'/2, l='MpServer', x=84.30, y=78.00, z=94.30], EntitySkeletonHorse['Skeleton Horse'/3, l='MpServer', x=84.27, y=78.00, z=92.58], EntitySkeletonHorse['Skeleton Horse'/4, l='MpServer', x=83.10, y=79.00, z=90.45], EntitySkeletonHorse['Skeleton Horse'/5, l='MpServer', x=82.46, y=78.00, z=92.79], EntityChicken['Chicken'/6, l='MpServer', x=83.21, y=78.00, z=91.66], EntityChicken['Chicken'/7, l='MpServer', x=80.20, y=78.00, z=90.28], EntityChicken['Chicken'/8, l='MpServer', x=80.88, y=78.00, z=90.35], EntitySpider['Spider'/297996, l='MpServer', x=132.50, y=89.00, z=56.50], EntityChicken['Chicken'/9, l='MpServer', x=81.27, y=78.00, z=93.19], EntityChicken['Chicken'/10, l='MpServer', x=84.11, y=78.00, z=90.64], EntitySkeletonHorse['Skeleton Horse'/11, l='MpServer', x=80.70, y=78.00, z=91.32], EntityColoredItemFrame['Colored Item Frame'/15, l='MpServer', x=105.50, y=77.50, z=74.03], EntitySpark['Spark'/17, l='MpServer', x=113.50, y=94.50, z=53.50], EntityWorm['Worm'/18, l='MpServer', x=45.50, y=69.50, z=64.50], EntityWorm['Worm'/19, l='MpServer', x=45.50, y=69.50, z=70.50], EntityColoredItemFrame['Colored Item Frame'/20, l='MpServer', x=50.03, y=85.50, z=85.50], EntityColoredItemFrame['Colored Item Frame'/21, l='MpServer', x=50.03, y=84.50, z=85.50], EntityBat['Bat'/274962, l='MpServer', x=85.54, y=61.57, z=99.96], EntityWorm['Worm'/23, l='MpServer', x=50.50, y=69.50, z=65.50], EntityWorm['Worm'/24, l='MpServer', x=51.50, y=69.50, z=70.50], EntityColoredItemFrame['Colored Item Frame'/25, l='MpServer', x=55.50, y=72.50, z=111.97], EntityZombie['Zombie'/254234, l='MpServer', x=125.50, y=70.00, z=32.50], EntityItemFrame['entity.ItemFrame.name'/26, l='MpServer', x=61.03, y=84.50, z=58.50], EntitySkeleton['Skeleton'/257311, l='MpServer', x=109.50, y=79.00, z=31.50], EntityCreeper['Creeper'/219947, l='MpServer', x=119.30, y=72.00, z=35.70], EntityPigZombie['Zombie Pigman'/42, l='MpServer', x=90.54, y=90.00, z=41.78], EntityBat['Bat'/184880, l='MpServer', x=102.00, y=20.03, z=114.84], EntityXPOrb['Experience Orb'/278846, l='MpServer', x=96.25, y=89.00, z=51.37], EntityXPOrb['Experience Orb'/278847, l='MpServer', x=96.24, y=89.00, z=50.42], EntityMinecartEmpty['entity.MinecartRideable.name'/66, l='MpServer', x=91.50, y=96.06, z=45.51], EntityXPOrb['Experience Orb'/278848, l='MpServer', x=95.93, y=89.00, z=52.41], EntityItem['item.item.feather'/275277, l='MpServer', x=82.52, y=78.00, z=94.88], EntityPlayerSP['armelin1'/64189, l='MpServer', x=98.69, y=89.00, z=61.47], EntitySkeleton['Skeleton'/272502, l='MpServer', x=146.50, y=68.00, z=20.50], EntitySkeleton['Skeleton'/226935, l='MpServer', x=54.50, y=55.00, z=123.50], EntitySkeleton['Skeleton'/226934, l='MpServer', x=54.50, y=55.00, z=123.50], EntitySlime['Slime'/278910, l='MpServer', x=96.98, y=16.00, z=39.98], EntitySkeleton['Skeleton'/226936, l='MpServer', x=54.35, y=55.00, z=122.04], EntitySkeleton['Skeleton'/278914, l='MpServer', x=160.50, y=13.00, z=69.50], EntityColoredItemFrame['Colored Item Frame'/28303, l='MpServer', x=95.50, y=72.50, z=72.03], EntitySpider['Spider'/272541, l='MpServer', x=125.50, y=89.00, z=33.50], EntityCreeper['Creeper'/278687, l='MpServer', x=103.30, y=17.00, z=37.70], EntityCreeper['Creeper'/278682, l='MpServer', x=77.86, y=79.00, z=65.75], EntityPig['Pig'/179, l='MpServer', x=39.52, y=79.00, z=28.71], EntitySheep['Sheep'/180, l='MpServer', x=37.52, y=83.00, z=39.23], EntityWorm['Worm'/184, l='MpServer', x=62.50, y=74.50, z=17.50], EntityWorm['Worm'/185, l='MpServer', x=62.50, y=74.50, z=23.50], EntityWorm['Worm'/186, l='MpServer', x=62.50, y=74.50, z=20.50], EntityWorm['Worm'/188, l='MpServer', x=68.50, y=74.50, z=17.50], EntitySheep['Sheep'/192, l='MpServer', x=110.55, y=80.00, z=3.55], EntitySpark['Spark'/193, l='MpServer', x=101.50, y=90.50, z=47.50], EntitySpark['Spark'/194, l='MpServer', x=102.50, y=90.50, z=47.50], EntitySpark['Spark'/195, l='MpServer', x=103.50, y=90.50, z=47.50], EntitySpark['Spark'/196, l='MpServer', x=99.50, y=90.50, z=41.50], EntitySpark['Spark'/197, l='MpServer', x=105.50, y=90.50, z=41.50], EntitySpark['Spark'/198, l='MpServer', x=97.50, y=91.50, z=45.50], EntitySpark['Spark'/199, l='MpServer', x=105.50, y=90.50, z=47.50], EntitySpark['Spark'/200, l='MpServer', x=104.50, y=90.50, z=47.50], EntitySkeleton['Skeleton'/307916, l='MpServer', x=114.50, y=33.00, z=74.50], EntitySpark['Spark'/201, l='MpServer', x=104.50, y=90.50, z=46.50], EntityCreeper['Creeper'/307917, l='MpServer', x=114.30, y=33.00, z=73.30], EntitySpark['Spark'/202, l='MpServer', x=104.50, y=90.50, z=45.50], EntityCyberZombie['Cyberzombie'/307918, l='MpServer', x=115.66, y=33.00, z=73.56], EntitySpark['Spark'/203, l='MpServer', x=105.50, y=90.50, z=45.50], EntitySpark['Spark'/204, l='MpServer', x=105.50, y=90.50, z=46.50], EntitySpark['Spark'/205, l='MpServer', x=103.50, y=90.50, z=45.50], EntitySpark['Spark'/206, l='MpServer', x=103.50, y=90.50, z=46.50], EntitySpark['Spark'/207, l='MpServer', x=102.50, y=90.50, z=46.50], EntitySpark['Spark'/208, l='MpServer', x=102.50, y=90.50, z=45.50], EntitySpark['Spark'/209, l='MpServer', x=101.50, y=90.50, z=45.50], EntitySpark['Spark'/210, l='MpServer', x=101.50, y=90.50, z=46.50], EntitySpark['Spark'/211, l='MpServer', x=101.50, y=90.50, z=49.50], EntitySpark['Spark'/212, l='MpServer', x=101.50, y=90.50, z=48.50], EntitySpark['Spark'/213, l='MpServer', x=102.50, y=90.50, z=48.50], EntitySpark['Spark'/214, l='MpServer', x=102.50, y=90.50, z=49.50], EntitySpark['Spark'/215, l='MpServer', x=103.50, y=90.50, z=49.50], EntitySpark['Spark'/216, l='MpServer', x=103.50, y=90.50, z=48.50], EntitySpark['Spark'/217, l='MpServer', x=98.50, y=90.50, z=52.50], EntitySpark['Spark'/218, l='MpServer', x=99.50, y=90.50, z=58.50], EntitySpark['Spark'/219, l='MpServer', x=104.50, y=90.50, z=48.50], EntitySpark['Spark'/220, l='MpServer', x=104.50, y=90.50, z=49.50], EntitySpark['Spark'/221, l='MpServer', x=105.50, y=90.50, z=48.50], EntitySpark['Spark'/222, l='MpServer', x=105.50, y=90.50, z=49.50], EntitySpark['Spark'/223, l='MpServer', x=105.50, y=90.50, z=52.50], EntityBat['Bat'/130782, l='MpServer', x=136.11, y=34.45, z=105.61], EntityCow['Cow'/224, l='MpServer', x=115.45, y=90.00, z=37.45], EntitySpark['Spark'/225, l='MpServer', x=112.50, y=90.50, z=42.50], EntityItem['item.item.egg'/42218, l='MpServer', x=80.20, y=78.00, z=92.93], EntityItem['item.item.feather'/283374, l='MpServer', x=80.13, y=78.00, z=90.13], EntityZombie['Zombie'/291566, l='MpServer', x=35.50, y=79.00, z=108.50], EntityItem['item.item.fish.salmon.raw'/280054, l='MpServer', x=90.72, y=80.06, z=76.83], EntitySpider['Spider'/291571, l='MpServer', x=68.50, y=83.00, z=117.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge,sponge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:393)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_92, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 552915200 bytes (527 MB) / 2420637696 bytes (2308 MB) up to 3340763136 bytes (3186 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx3584m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.38 Powered by Forge 13.20.0.2282 Optifine OptiFine_1.11.2_HD_U_B7 77 mods loaded, 77 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2282-universal.jar) 
	UCHIJA	forge{13.20.0.2282} [Minecraft Forge] (forge-1.11.2-13.20.0.2282-universal.jar) 
	UCHIJA	aroma1997core{${version}} [Aroma1997Core] (Aroma1997Core-1.11.2-1.2.0.0.b81.jar) 
	UCHIJA	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHIJA	unborked_core{1.1.4} [Unborked Core] (minecraft.jar) 
	UCHIJA	<CCTweaks ASM>{1.3.3} [<CCTweaks ASM>] (minecraft.jar) 
	UCHIJA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.11.2-2.6.0.254-universal.jar) 
	UCHIJA	actuallyadditions{1.11.2-r106} [Actually Additions] (ActuallyAdditions-1.11.2-r106.jar) 
	UCHIJA	akashictome{1.1-7} [Akashic Tome] (AkashicTome-1.1-7.jar) 
	UCHIJA	jei{4.3.3.266} [Just Enough Items] (jei_1.11.2-4.3.3.266.jar) 
	UCHIJA	appleskin{1.0.6} [AppleSkin] (AppleSkin-mc1.11-1.0.6.jar) 
	UCHIJA	aroma1997corehelper{1.0} [Aroma1997Core|Helper] (Aroma1997Core-1.11.2-1.2.0.0.b81.jar) 
	UCHIJA	aromabackup{1.0} [AromaBackup] (AromaBackup-1.11-2.1.0.0.b64.jar) 
	UCHIJA	aromabackuprecovery{1.0} [AromaBackupRecovery] (AromaBackup-1.11-2.1.0.0.b64.jar) 
	UCHIJA	morphtool{1.1-13} [Morph-o-Tool] (Morph-o-Tool-1.1-13.jar) 
	UCHIJA	psi{r1.1-47} [Psi] (Psi-r1.1-47.jar) 
	UCHIJA	quark{r1.2-90} [Quark] (Quark-r1.2-90.jar) 
	UCHIJA	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHIJA	baubles{1.4.3} [Baubles] (Baubles-1.11-1.4.3.jar) 
	UCHIJA	betterachievements{0.4.1.44} [Better Achievements] (BetterAchievements-1.11.2-0.4.1.44.jar) 
	UCHIJA	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.11-0.11.1.239+9162f74.jar) 
	UCHIJA	betterthanmending{@VERSION@} [Better Than Mending] (BetterThanMending-1.1.0.jar) 
	UCHIJA	bookshelf{1.5.0.369} [Bookshelf] (Bookshelf-1.11.2-1.5.0.369.jar) 
	UCHIJA	botania{r1.9-342} [Botania] (Botania r1.9-342.jar) 
	UCHIJA	computercraft{1.80pr0} [ComputerCraft] (ComputerCraft1.80pr0-patched-DO-NOT-DISTRIBUTE.jar) 
	UCHIJA	mekanism{9.3.0} [Mekanism] (Mekanism-1.11.2-9.3.0.homebaked.jar) 
	UCHIJA	rftools{6.00} [RFTools] (rftools-1.1x-6.00.jar) 
	UCHIJA	brjplayutils{1.1} [BRjPlay Utils] (brjplayutils-1.1.jar) 
	UCHIJA	cctweaks{1.3.3} [CCTweaks] (CCTweaks-1.11.2-1.3.3.jar) 
	UCHIJA	chameleon{1.11-3.0.2} [Chameleon] (Chameleon-1.11-3.0.2.jar) 
	UCHIJA	codechickenlib{2.6.0.254} [CodeChicken Lib] (CodeChickenLib-1.11.2-2.6.0.254-universal.jar) 
	UCHIJA	chickenchunks{2.3.0.63} [ChickenChunks] (ChickenChunks-1.11.2-2.3.0.63-universal.jar) 
	UCHIJA	neat{1.4-13} [Neat] (client-Neat 1.4-13.jar) 
	UCHIJA	cosmeticarmorreworked{1.11.2-v1a} [CosmeticArmorReworked] (CosmeticArmorReworked-1.11.2-v1a.jar) 
	UCHIJA	cyberware{alpha-0.2.9} [Cyberware] (cyberware-1.11.2-alpha-0.2.9.jar) 
	UCHIJA	darkutils{1.2.0.134} [Dark Utilities] (DarkUtilities-1.11.2-1.2.0.134.jar) 
	UCHIJA	durabilityshow{4.1.0} [Durability Show] (Durability Show-1.11.2-4.1.0.jar) 
	UCHIJA	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod-1.11.2-1.3.0.jar) 
	UCHIJA	enderstorage{1.0} [EnderStorage] (EnderStorage-1.11.2-2.3.0.112-universal.jar) 
	UCHIJA	shetiphiancore{3.4.4} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.4.jar) 
	UCHIJA	endertanks{1.5.4} [EnderTanks] (endertanks-1.11.0-1.5.4.jar) 
	UCHIJA	valkyrielib{1.11.2-0.11.0b} [Valkyrie Lib] (valkyrielib-1.11.2-0.11.0c.jar) 
	UCHIJA	environmentaltech{1.11.2-0.11.0d} [Environmental Tech] (environmentaltech-1.11.2-0.11.0d.jar) 
	UCHIJA	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.4.jar) 
	UCHIJA	zerocore{1.11.2-0.1.0.4} [Zero CORE] (zerocore-1.11.2-0.1.0.4.jar) 
	UCHIJA	bigreactors{1.11.2-0.4.5.27} [Extreme Reactors] (ExtremeReactors-1.11.2-0.4.5.27.jar) 
	UCHIJA	fastleafdecay{v12} [Fast Leaf Decay] (FastLeafDecay-v12.jar) 
	UCHIJA	foamfix{@VERSION@} [FoamFix] (foamfix-0.6.2-beta4-anarchy.jar) 
	UCHIJA	inventorypets{1.4.9.4} [Inventory Pets] (inventorypets-1.11.2-1.4.9.4.jar) 
	UCHIJA	inventorytweaks{1.62-dev-75-f4ba194} [Inventory Tweaks] (InventoryTweaks-1.62-dev-75.jar) 
	UCHIJA	itemscroller{0.10.3} [Item Scroller] (itemscroller-1.11.2-0.10.3.jar) 
	UCHIJA	journeymap{1.11.2-5.4.4} [JourneyMap] (journeymap-1.11.2-5.4.4.jar) 
	UCHIJA	jeresources{0.6.2.104} [Just Enough Resources] (JustEnoughResources-1.11.2-0.6.2.104.jar) 
	UCHIJA	llor{1.1.3-mc1.11.2} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.3-mc1.11.2.jar) 
	UCHIJA	mekanismgenerators{9.3.0} [MekanismGenerators] (MekanismGenerators-1.11.2-9.3.0.homebaked.jar) 
	UCHIJA	mekanismtools{9.3.0} [MekanismTools] (MekanismTools-1.11.2-9.3.0.homebaked.jar) 
	UCHIJA	multistorage{1.3.6} [Multi-Storage] (multistorage-1.11.0-1.3.6.jar) 
	UCHIJA	nei{${mod_version}} [Not Enough Items] (NotEnoughItems-1.11.2-2.2.0.217-universal.jar) 
	UCHIJA	omlib{1.11.2-3.0.0-61} [OMLib] (omlib-1.11.2-3.0.0-61.jar) 
	UCHIJA	opencomputers{1.7.0.6} [OpenComputers] (OpenComputers-MC1.11.2-1.7.0.6.jar) 
	UCHIJA	fodc{1.10.0} [Ore Dictionary Converter] (OreDictionaryConverter-1.10.0.jar) 
	UCHIJA	reborncore{2.14.0.81} [RebornCore] (RebornCore-1.11.2-2.14.0.81-universal.jar) 
	UCHIJA	quantumstorage{4.1.2} [QuantumStorage] (QuantumStorage-1.11.2-4.1.2.jar) 
	UCHIJA	rangedpumps{0.4} [Ranged Pumps] (rangedpumps-0.4.jar) 
	UCHIJA	reborncore-mcmultipart{2.14.0.81} [reborncore-MCMultiPart] (RebornCore-1.11.2-2.14.0.81-universal.jar) 
	UCHIJA	refinedstorage{1.4.2} [Refined Storage] (refinedstorage-1.4.2.jar) 
	UCHIJA	scenter{1.11.2-3.10.1} [Scenter] (scenter-1.11.2-3.10.1.jar) 
	UCHIJA	storagedrawers{1.11.2-4.2.2} [Storage Drawers] (StorageDrawers-1.11.2-4.2.2.jar) 
	UCHIJA	tellme{0.5.2} [Tell Me] (tellme-1.11.2-0.5.2.jar) 
	UCHIJA	theoneprobe{1.4.6} [The One Probe] (theoneprobe-1.1x-1.4.6.jar) 
	UCHIJA	tp{2.0.2} [Tiny Progressions] (tinyprogressions-1.11.2-2.0.2 (1).jar) 
	UCHIJA	topaddons{1.11.2-0.9.2} [TOP Addons] (topaddons-1.11.2-0.9.2.jar) 
	UCHIJA	translocator{2.2.0.59} [Translocator] (Translocators-1.11.2-2.2.0.59-universal.jar) 
	UCHIJA	unborked{1.1.4} [Unborked] (unborked-1.11.2-1.80pr0-1.1.4.jar) 
	UCHIJA	xnet{1.3.1} [XNet] (xnet-1.3.1.jar) 
	Loaded coremods (and transformers): 
TweaksLoadingPlugin (CCTweaks-1.11.2-1.3.3.jar)
  org.squiddev.cctweaks.core.asm.ASMTransformer
RebornCoreASM (RebornCore-1.11.2-2.14.0.81-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
BookshelfLoadingPlugin (Bookshelf-1.11.2-1.5.0.369.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
NEICorePlugin (NotEnoughItems-1.11.2-2.2.0.217-universal.jar)
  codechicken.nei.asm.NEITransformer
CCLCorePlugin (CodeChickenLib-1.11.2-2.6.0.254-universal.jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
UnborkedPlugin (unborked-1.11.2-1.80pr0-1.1.4.jar)
  org.squiddev.unborked.core.UnborkedTransformer
LoadingPlugin (Quark-r1.2-90.jar)
  vazkii.quark.base.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.62-dev-75.jar)
  invtweaks.forge.asm.ContainerTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.2-beta4-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.4.jar)
  shetiphian.core.asm.ClassTransformer
CoreMod (Aroma1997Core-1.11.2-1.2.0.0.b81.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.1.11156 Compatibility Profile Context' Renderer: 'AMD Radeon(TM) HD 6620G'
	chickenchunks Invalid Fingerprint Reports: - No invalid fingerprints.: 
	enderstorage Invalid Fingerprint Reports: - No invalid fingerprints.: 
	nei Invalid Fingerprint Reports: - No invalid fingerprints.: 
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 2.14.0.81
		Mixin Status: 1
		Runtime Debofucsation 1
		RenderEngine: 1
	translocator Invalid Fingerprint Reports: - No invalid fingerprints.: 
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: AMD Radeon(TM) HD 6620G GL version 4.1.11156 Compatibility Profile Context, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A8-3520M APU with Radeon(tm) HD Graphics
	OptiFine Version: OptiFine_1.11.2_HD_U_B7
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.1.11156 Compatibility Profile Context
	OpenGlRenderer: AMD Radeon(TM) HD 6620G
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4
```

**Comment by capnkirok** [comment]
Thanks for the report. Can you tell me what you were doing when this happened? I assume you were trying to open the pet double chest... but what else was happening. The crash report says you were clicking on an AIR block.

~~Were you on server or single player?~~

**Comment by capnkirok** [comment]
I can't reproduce this, but I put in an 'Air Check' so it shouldn't happen again.
