### ISSUE TITLE
[1.11.2 only] Crash when Opening Feedbag

### ISSUE THREAD

**Issue by aelfwyne** [capnkirok/Inventory-Pets#193]
Minecraft 1.11.2
Inventory-Pets 1496

Upgraded from 1495 version of InventoryPets.

When I open the Feedbag, now the client crashes.

> Stacktrace:
	at com.inventorypets.gui.GuiFeedBag.func_146979_b(GuiFeedBag.java:50)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:118)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:547)

https://paste.ee/p/axFeu

**Comment by capnkirok** [comment]
Yep, I put something dumb in. Fix coming shortly.

**Comment by capnkirok** [comment]
Ok this is fixed an now live.
