### ISSUE TITLE
[1.7.10] Client disconnection related to spider pet

### ISSUE THREAD

**Issue by LemADEC** [capnkirok/Inventory-Pets#233]
As of inventorypets-1.7.10-1.4.9.9b-universal.jar, we can see this logs in console:
```
[01:29:57 WARN]: Failed to handle packet for /69.137.236.195:50079
net.minecraft.util.ReportedException: Ticking player
>       at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:477) ~[mw.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:488) ~[nh.class:?]
>       at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36) ~[jd.class:?]
>       at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(C03PacketPlayer.java:234) ~[jf.class:?]
>       at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) ~[ej.class:?]
>       at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.EntityPlayer.func_70016_h(DDD)V
>       at com.inventorypets.PlayerTickHandler.onLivingUpdateEvent(PlayerTickHandler.java:117) ~[PlayerTickHandler.class:?]
>       at cpw.mods.fml.common.eventhandler.ASMEventHandler_689_PlayerTickHandler_onLivingUpdateEvent_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
>       at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.57]
>       at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:1.7.10-1614.57]
>       at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:298) ~[ForgeHooks.class:1.7.10-1614.57]
>       at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1901) ~[sv.class:?]
>       at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:315) ~[yz.class:?]
>       at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:399) ~[mw.class:?]
>       ... 10 more
```
From a quick code review, it seems related to using Sneak + Spider pet.

**Comment by capnkirok** [comment]
Wow, this code has been in here form the original version (3 years ago).

**Comment by capnkirok** [comment]
Fixed in next release. Only would have occurred on servers.

**Comment by capnkirok** [comment]
Only on 1.7.10
