### ISSUE TITLE
patreonShirt.func_7763_a NoSuchMethod

### ISSUE THREAD

**Issue by payonel** [capnkirok/Inventory-Pets#256]
forge: forge-1.12.2-14.23.4.2705-universal.jar
inventory pets: inventorypets-1.12-1.5.1.jar
and then we tried to resolve it (in vain) by updating to inventorypets-1.12-1.5.2.jar

We have a player that just was awarded the pateronShirt from the illuminati pet and was kicked from the server

The interseting bits of the stack trace
```
[19:53:11] [Server thread/WARN] [net.minecraft.network.NetworkSystem]: Failed to handle packet for /192.168.8.1:52345
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
...
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
        at com.inventorypets.items.patreonShirt.func_77663_a(patreonShirt.java:53) ~[patreonShirt.class:?]
        at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:526) ~[aip.class:?]
        ... more
```
full stack as printed:

```
[19:53:13] [Server thread/WARN] [net.minecraft.network.NetworkSystem]: Failed to handle packet for /192.168.8.1:52345
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
        at com.inventorypets.items.patreonShirt.func_77663_a(patreonShirt.java:53) ~[patreonShirt.class:?]
        at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:526) ~[aip.class:?]
        at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:363) ~[aec.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:511) ~[aed.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
        ... 9 more
```

I'm going to update forge and retest
Then, I'll try to remove the item from the player dat file manually

**Comment by payonel** [comment]
retested with forge 2725, same connection-crash (forcing client to logout). going to try to remove the item manually

**Comment by payonel** [comment]
I'm removing this from the player dat
![image](https://user-images.githubusercontent.com/6590223/42011103-c09e6856-7a46-11e8-83cc-30b94c4d4d0e.png)
will retest and report

**Comment by payonel** [comment]
Ok that fixed it (having removed the inventorypets:patreon_shirt)

**Comment by capnkirok** [comment]
I never thought of this scenario, silly me. I will remove it from the pool of possibilities.

**Comment by capnkirok** [comment]
Ok, added to the blacklist.
