### ISSUE TITLE
Crash casting TNT entity to EntityLivingBase

### ISSUE THREAD

**Issue by TheWyo** [capnkirok/Inventory-Pets#266]
Just had this while playing the Foolcraft 3 pack. Chance cube spawned a TNT riding an ocelot. Not found any inventory pets yet on this world.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LibLoader (# LibLoader.jar)
  RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  ForgelinPlugin (Forgelin-1.7.4.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.1.16.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  AstralCore (astralsorcery-1.12.2-1.9.3.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.35.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  CoreMod (TickProfiler-1.12-0.0.4.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  ObfuscatePlugin (obfuscate-0.2.4-1.12.2.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 7/15/18 8:46 PM
Description: Ticking entity

java.lang.ClassCastException: net.minecraft.entity.item.EntityTNTPrimed cannot be cast to net.minecraft.entity.EntityLivingBase
	at com.inventorypets.events.ItemEntityEvents.travel(ItemEntityEvents.java:103)
	at com.inventorypets.events.ItemEntityEvents.handleLivingUpdateEvent(ItemEntityEvents.java:90)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2041_ItemEntityEvents_handleLivingUpdateEvent_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:566)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2086)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.inventorypets.events.ItemEntityEvents.travel(ItemEntityEvents.java:103)
	at com.inventorypets.events.ItemEntityEvents.handleLivingUpdateEvent(ItemEntityEvents.java:90)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2041_ItemEntityEvents_handleLivingUpdateEvent_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:566)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2086)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: minecraft:ocelot (net.minecraft.entity.passive.EntityOcelot)
	Entity ID: 548
	Entity Name: Ocelot
	Entity's Exact location: 463.00, 72.00, 245.00
	Entity's Block location: World: (463,72,245), Chunk: (at 15,4,5 in 28,15; contains blocks 448,0,240 to 463,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: [EntityTNTPrimed['Block of TNT'/549, l='Main', x=463.00, y=72.00, z=245.00]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Main
	All players: 1 total; [EntityPlayerMP['TheWyo'/357, l='Main', x=465.44, y=70.00, z=240.82]]
	Chunk stats: ServerChunkCache: 1250 Drop: 0
	Level seed: -1308804484864063873
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (68,64,256), Chunk: (at 4,4,0 in 4,16; contains blocks 64,0,256 to 79,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 144584 game time, 192195 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 63510 (now: false), thunder time: 45685 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by capnkirok** [comment]
Related to #260

**Comment by capnkirok** [comment]
Fixed in next release
