### ISSUE TITLE
[1.12.2] Disabling Advancements not working in Server environment

### ISSUE THREAD

**Issue by flamechair** [capnkirok/Inventory-Pets#282]
This causes several long stack traces to appear in the console log, for each world loaded:

Minecraft: 1.12.2
SF version: spongeforge-1.12.2-2705-7.1.0-BETA-3406
Inventory Pets: inventorypets-1.12-1.5.3.1

Some examples:
```
[20:08:12] [Server thread/ERROR] [FML]: Parsing error loading built-in advancement inventorypets:inventorypets/fan
com.google.gson.JsonSyntaxException: Unknown item id 'inventorypets:silverfish_pet'
at net.minecraft.advancements.critereon.ItemPredicate.deserialize(ItemPredicate.java:127) ~[an.class:?]
at net.minecraft.advancements.critereon.ItemPredicate.deserializeArray(ItemPredicate.java:163) ~[an.class:?]
at net.minecraft.advancements.critereon.InventoryChangeTrigger.deserializeInstance(SourceFile:62) ~[al.class:?]
at net.minecraft.advancements.critereon.InventoryChangeTrigger.deserializeInstance(SourceFile:21) ~[al.class:?]
at net.minecraft.advancements.Criterion.criterionFromJson(SourceFile:35) ~[n.class:?]
at net.minecraft.advancements.Criterion.criteriaFromJson(SourceFile:46) ~[n.class:?]
at net.minecraft.advancements.Advancement$Builder.deserialize(SourceFile:204) ~[i$a.class:?]
at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
at net.minecraft.util.JsonUtils.gsonDeserialize(SourceFile:492) ~[rc.class:?]
at net.minecraft.util.JsonUtils.fromJson(SourceFile:532) ~[rc.class:?]
at net.minecraftforge.common.ForgeHooks.lambda$loadAdvancements$0(ForgeHooks.java:1357) ~[ForgeHooks.class:?]
at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:821) [CraftingHelper.class:?]
at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1339) [ForgeHooks.class:?]
at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1313) [ForgeHooks.class:?]
at net.minecraft.advancements.AdvancementManager.reload(AdvancementManager.java:69) [ns.class:?]
at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
at net.minecraft.world.WorldServer.init(WorldServer.java:156) [oo.class:?]
at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:796) [WorldManager.class:1.12.2-2705-7.1.0-BETA-3406]
at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:764) [WorldManager.class:1.12.2-2705-7.1.0-BETA-3406]
at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:3545) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:270) [nz.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```
```
[20:08:12] [Server thread/ERROR] [FML]: Parsing error loading built-in advancement inventorypets:inventorypets/legend
com.google.gson.JsonSyntaxException: Expected item to be an item, was unknown string 'inventorypets:black_hole_pet'
at net.minecraft.util.JsonUtils.getItem(SourceFile:124) ~[rc.class:?]
at net.minecraft.util.JsonUtils.getItem(SourceFile:135) ~[rc.class:?]
at net.minecraft.advancements.DisplayInfo.deserializeIcon(DisplayInfo.java:133) ~[r.class:?]
at net.minecraft.advancements.DisplayInfo.deserialize(DisplayInfo.java:111) ~[r.class:?]
at net.minecraft.advancements.Advancement$Builder.deserialize(SourceFile:202) ~[i$a.class:?]
at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
at net.minecraft.util.JsonUtils.gsonDeserialize(SourceFile:492) ~[rc.class:?]
at net.minecraft.util.JsonUtils.fromJson(SourceFile:532) ~[rc.class:?]
at net.minecraftforge.common.ForgeHooks.lambda$loadAdvancements$0(ForgeHooks.java:1357) ~[ForgeHooks.class:?]
at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:821) [CraftingHelper.class:?]
at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1339) [ForgeHooks.class:?]
at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1313) [ForgeHooks.class:?]
at net.minecraft.advancements.AdvancementManager.reload(AdvancementManager.java:69) [ns.class:?]
at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
at net.minecraft.world.WorldServer.init(WorldServer.java:156) [oo.class:?]
at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:796) [WorldManager.class:1.12.2-2705-7.1.0-BETA-3406]
at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:764) [WorldManager.class:1.12.2-2705-7.1.0-BETA-3406]
at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:3545) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:270) [nz.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```
```
[20:08:12] [Server thread/ERROR] [FML]: Parsing error loading built-in advancement inventorypets:inventorypets/specialist
com.google.gson.JsonSyntaxException: Unknown item id 'inventorypets:purplicious_cow_pet'
at net.minecraft.advancements.critereon.ItemPredicate.deserialize(ItemPredicate.java:127) ~[an.class:?]
at net.minecraft.advancements.critereon.ItemPredicate.deserializeArray(ItemPredicate.java:163) ~[an.class:?]
at net.minecraft.advancements.critereon.InventoryChangeTrigger.deserializeInstance(SourceFile:62) ~[al.class:?]
at net.minecraft.advancements.critereon.InventoryChangeTrigger.deserializeInstance(SourceFile:21) ~[al.class:?]
at net.minecraft.advancements.Criterion.criterionFromJson(SourceFile:35) ~[n.class:?]
at net.minecraft.advancements.Criterion.criteriaFromJson(SourceFile:46) ~[n.class:?]
at net.minecraft.advancements.Advancement$Builder.deserialize(SourceFile:204) ~[i$a.class:?]
at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
at net.minecraft.util.JsonUtils.gsonDeserialize(SourceFile:492) ~[rc.class:?]
at net.minecraft.util.JsonUtils.fromJson(SourceFile:532) ~[rc.class:?]
at net.minecraftforge.common.ForgeHooks.lambda$loadAdvancements$0(ForgeHooks.java:1357) ~[ForgeHooks.class:?]
at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:821) [CraftingHelper.class:?]
at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1339) [ForgeHooks.class:?]
at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1313) [ForgeHooks.class:?]
at net.minecraft.advancements.AdvancementManager.reload(AdvancementManager.java:69) [ns.class:?]
at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
at net.minecraft.world.WorldServer.init(WorldServer.java:156) [oo.class:?]
at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:796) [WorldManager.class:1.12.2-2705-7.1.0-BETA-3406]
at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:764) [WorldManager.class:1.12.2-2705-7.1.0-BETA-3406]
at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:3545) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:270) [nz.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by flamechair** [comment]
Also disabling advancements in the config does not solve this issue either

**Comment by capnkirok** [comment]
Might be a Sponge issue or a 'something dumb I did recently' issue. Will take a look, thanks for posting.

**Comment by capnkirok** [comment]
Ok, turns out it's neither of these things. Has nothing to do with Sponge, and nothing to do with something I did recently. 

Disabling advancements does not seem to work in a 1.12.2 Server environment currently. Could be a recent forge change. Surprised no one has caught it until now.

**Comment by capnkirok** [comment]
I'm actually removing this from the config. The only way to truly do this is to make all achievements custom, using 'impossible', and then trigger them via custom events.
