### ISSUE TITLE
Client crash with chest pet

### ISSUE THREAD

**Issue by LemADEC** [capnkirok/Inventory-Pets#283]
As observed with 1.12-1.5.3.1, random client crash happens when opening chest pest

```
java.lang.ClassCastException: net.minecraft.item.ItemAir cannot be cast to com.inventorypets.pets.petDoubleChest
    at com.inventorypets.gui.GuiDoubleChestPet.drawGuiContainerBackgroundLayer(GuiDoubleChestPet.java:36)
    at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:75)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1124)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1118)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3940)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by capnkirok** [comment]
Alright, I've removed the offending code.
