### ISSUE TITLE
ArrayIndexOutOfBoundsException: 500

### ISSUE THREAD

**Issue by judgekreep** [capnkirok/Inventory-Pets#336]
There is an incompatibility between BetterQuesting 3.0.306 (1.7.10) and InventoryPets 1.5.2 (1.7.10).

I receive this crash log when clicking on any item within the item selection screen of BetterQuesting (reward, icon, etc).
Works fine when I take off the Inventory Pets mod.
* I tested in a new world, with new config files.

I was told: "This appears to be an issue with inventory pet's tootltip handling and not a BQ issue."

java.lang.ArrayIndexOutOfBoundsException: 500
at com.inventorypets.petCustom.func_77624_a(petCustom.java:554)
at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:525)
at betterquesting.api2.client.gui.panels.content.PanelItemSlot.setStoredValue(PanelItemSlot.java:57)
at betterquesting.api2.client.gui.panels.content.PanelItemSlot.setStoredValue(PanelItemSlot.java:21)
at betterquesting.api2.client.gui.controls.PanelButtonStorage.(PanelButtonStorage.java:14)
at betterquesting.api2.client.gui.panels.content.PanelItemSlot.(PanelItemSlot.java:40)
at betterquesting.api2.client.gui.panels.content.PanelItemSlot.(PanelItemSlot.java:30)
at betterquesting.api2.client.gui.panels.lists.CanvasItemDatabase.addResult(CanvasItemDatabase.java:121)
at betterquesting.api2.client.gui.panels.lists.CanvasItemDatabase.addResult(CanvasItemDatabase.java:21)
at betterquesting.api2.client.gui.panels.lists.CanvasSearch.updateResults(CanvasSearch.java:92)
at betterquesting.api2.client.gui.panels.lists.CanvasSearch.drawPanel(CanvasSearch.java:41)
at betterquesting.api2.client.gui.panels.CanvasEmpty.drawPanel(CanvasEmpty.java:52)
at betterquesting.api2.client.gui.panels.CanvasEmpty.drawPanel(CanvasEmpty.java:52)
at betterquesting.api2.client.gui.panels.CanvasTextured.drawPanel(CanvasTextured.java:27)
at betterquesting.api2.client.gui.GuiScreenCanvas.drawPanel(GuiScreenCanvas.java:209)
at betterquesting.api2.client.gui.GuiScreenCanvas.func_73863_a(GuiScreenCanvas.java:124)
at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1455)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by capnkirok** [comment]
Yeah. That is an item that has been partially removed from the IP code. Frankly, BQ should have a way of error trapping this. BQ is looping through items from IP and trying to pull info. I can remove the item fully in a future update, but there's no reason BQ should be accessing this item in the first place.

**Comment by capnkirok** [comment]
Sadly, I can no longer update 1.7.10 because it is no longer supported.
