### ISSUE TITLE
Cloud pet make player kick out of server

### ISSUE THREAD

**Issue by Chrissdroid** [capnkirok/Inventory-Pets#359]
My friend just acquired the cloudpet with the illuminaty pet and then it can't connect anymore to the server. With an "internal server error" big red text on the client

```cmd
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:459) ~[oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:173) ~[pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
	at com.inventorypets.pets.petCloud.onUpdate(petCloud.java:132) ~[petCloud.class:?]
	at net.minecraft.item.ItemStack.updateAnimation(ItemStack.java:526) ~[aip.class:?]
	at net.minecraft.entity.player.InventoryPlayer.decrementAnimations(InventoryPlayer.java:363) ~[aec.class:?]
	at net.minecraft.entity.player.EntityPlayer.onLivingUpdate(EntityPlayer.java:511) ~[aed.class:?]
	at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:234) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:382) ~[oq.class:?]
	... 9 more
```

**Comment by AzaelCC** [comment]
For what is worth you can use an NBT editor and erase the cloud pet item from their inventory. I just had this problem doing some testing on my server and thats how I "solved it". At least I can get in the server again!

**Comment by capnkirok** [comment]
Which version of Minecraft and Inventory Pets is this?

**Comment by AzaelCC** [comment]
Not op, but I'm having it on Mc 1.12.2, Inventory pets 2.0.5, Forge 14.23.5.2847, Regular forge server.

**Comment by Chrissdroid** [comment]
> For what is worth you can use an NBT editor and erase the cloud pet item from their inventory. I just had this problem doing some testing on my server and thats how I "solved it". At least I can get in the server again!

Yeah i do that too with editing directly the user's .dat file in the map folder

**Comment by Chrissdroid** [comment]
> Which version of Minecraft and Inventory Pets is this?

minecraft 1.12.2, v2.0.5 of the mod and it's the cloud pet

**Comment by Polar30** [comment]
After troubleshooting with the same issue, I discovered that it kicks me from the server when the cloud pet enters my inventory, but it is totally fine in my hotbar. Running the same version of the mod and forge

**Comment by capnkirok** [comment]
Thank you @Polar30 that was very helpful. The crash happens only when the cloud pet is in the inventory... but not the hotbar. Working on a permanent fix now.

**Comment by capnkirok** [comment]
Ok, this will be fixed in the 2.0.6 update, coming out soon.

**Comment by Polar30** [comment]
@capnkirok Thanks! Glad I could help. Inventory pets has been one of my favorite mods for a really long time.

**Comment by AzaelCC** [comment]
@capnkirok Hey, when it happend to me the pet was in my hotbar, it kicked me out while flying and when using thunders after a short bit of time.

**Comment by Polar30** [comment]
@MrAce2C I’ve been using the mod for two days now, hasn’t happened to me

**Comment by AzaelCC** [comment]
@Polar30 I'll wait for the update then and if something happens I'll report back! May be an interaction with one of my server's mods. I disabled the pet after the other day.

**Comment by Polar30** [comment]
@capnkirok I just got kicked out twice after I used the lightning strike on the cloud pet. The timing is pretty inconsistent.

**Comment by capnkirok** [comment]
Yes, this is another way of reproducing the bug. But it's fixed now. Releasing later today!
