### ISSUE TITLE
Players Cannot Join Server

### ISSUE THREAD

**Issue by Time6628** [capnkirok/Inventory-Pets#36]
After updating inventory pets in the modpack crainer craft, it seems that playerdata is unable to be loaded or appended by InventoryPets.
Error:

```
[16:05:29] [Server thread/WARN]: java.lang.NullPointerException
[16:05:29] [Server thread/WARN]:    at com.inventorypets.IPHolidayExtendedPlayer.loadNBTData(IPHolidayExtendedPlayer.java:81)
[16:05:29] [Server thread/WARN]:    at net.minecraft.entity.Entity.func_70020_e(Entity.java:1650)
[16:05:29] [Server thread/WARN]:    at net.minecraft.world.storage.SaveHandler.func_75752_b(SaveHandler.java:314)
[16:05:29] [Server thread/WARN]:    at net.minecraft.server.management.ServerConfigurationManager.func_72380_a(ServerConfigurationManager.java:319)
[16:05:29] [Server thread/WARN]:    at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:147)
[16:05:29] [Server thread/WARN]:    at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:190)
[16:05:29] [Server thread/WARN]:    at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:465)
[16:05:29] [Server thread/WARN]:    at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:21)
[16:05:29] [Server thread/WARN]:    at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11)
[16:05:29] [Server thread/WARN]:    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
[16:05:29] [Server thread/WARN]:    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[16:05:29] [Server thread/WARN]:    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[16:05:29] [Server thread/WARN]:    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[16:05:29] [Server thread/WARN]:    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[16:05:29] [Server thread/WARN]:    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[16:05:29] [Server thread/WARN]:    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[16:05:29] [Server thread/WARN]:    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
[16:05:29] [Server thread/WARN]:    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
[16:05:29] [Server thread/WARN]:    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
[16:05:29] [Server thread/WARN]:    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
[16:05:29] [Server thread/WARN]:    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
[16:05:29] [Server thread/WARN]:    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991)
[16:05:29] [Server thread/WARN]:    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
[16:05:29] [Server thread/WARN]:    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
[16:05:29] [Server thread/WARN]:    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[16:05:29] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)
[16:05:29] [Server thread/ERROR]: Failed to load extended properties for IPGiftExtendedPlayer.  This is a mod issue.
[16:05:29] [Server thread/WARN]: java.lang.NullPointerException
[16:05:29] [Server thread/WARN]:    at com.inventorypets.IPGiftExtendedPlayer.loadNBTData(IPGiftExtendedPlayer.java:83)
[16:05:29] [Server thread/WARN]:    at net.minecraft.entity.Entity.func_70020_e(Entity.java:1650)
[16:05:29] [Server thread/WARN]:    at net.minecraft.world.storage.SaveHandler.func_75752_b(SaveHandler.java:314)
[16:05:29] [Server thread/WARN]:    at net.minecraft.server.management.ServerConfigurationManager.func_72380_a(ServerConfigurationManager.java:319)
[16:05:29] [Server thread/WARN]:    at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:147)
[16:05:29] [Server thread/WARN]:    at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:190)
[16:05:29] [Server thread/WARN]:    at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:465)
[16:05:29] [Server thread/WARN]:    at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:21)
[16:05:29] [Server thread/WARN]:    at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11)
[16:05:29] [Server thread/WARN]:    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
[16:05:29] [Server thread/WARN]:    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[16:05:29] [Server thread/WARN]:    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[16:05:29] [Server thread/WARN]:    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[16:05:29] [Server thread/WARN]:    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[16:05:29] [Server thread/WARN]:    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[16:05:29] [Server thread/WARN]:    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[16:05:29] [Server thread/WARN]:    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
[16:05:29] [Server thread/WARN]:    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
[16:05:29] [Server thread/WARN]:    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
[16:05:29] [Server thread/WARN]:    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
[16:05:29] [Server thread/WARN]:    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
[16:05:29] [Server thread/WARN]:    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991)
[16:05:29] [Server thread/WARN]:    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
[16:05:29] [Server thread/WARN]:    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
[16:05:29] [Server thread/WARN]:    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[16:05:29] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)
[16:05:29] [Server thread/ERROR]: Failed to load extended properties for IPCSxtendedPlayer.  This is a mod issue.
[16:05:29] [Server thread/WARN]: java.lang.NullPointerException
[16:05:29] [Server thread/WARN]:    at com.inventorypets.IPCSExtendedPlayer.loadNBTData(IPCSExtendedPlayer.java:52)
[16:05:29] [Server thread/WARN]:    at net.minecraft.entity.Entity.func_70020_e(Entity.java:1650)
[16:05:29] [Server thread/WARN]:    at net.minecraft.world.storage.SaveHandler.func_75752_b(SaveHandler.java:314)
[16:05:29] [Server thread/WARN]:    at net.minecraft.server.management.ServerConfigurationManager.func_72380_a(ServerConfigurationManager.java:319)
[16:05:29] [Server thread/WARN]:    at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:147)
[16:05:29] [Server thread/WARN]:    at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:190)
[16:05:29] [Server thread/WARN]:    at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:465)
[16:05:29] [Server thread/WARN]:    at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:21)
[16:05:29] [Server thread/WARN]:    at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11)
[16:05:29] [Server thread/WARN]:    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
[16:05:29] [Server thread/WARN]:    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[16:05:29] [Server thread/WARN]:    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[16:05:29] [Server thread/WARN]:    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[16:05:29] [Server thread/WARN]:    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[16:05:29] [Server thread/WARN]:    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[16:05:29] [Server thread/WARN]:    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[16:05:29] [Server thread/WARN]:    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
[16:05:29] [Server thread/WARN]:    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
[16:05:29] [Server thread/WARN]:    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
[16:05:29] [Server thread/WARN]:    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
[16:05:29] [Server thread/WARN]:    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
[16:05:29] [Server thread/WARN]:    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991)
[16:05:29] [Server thread/WARN]:    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
[16:05:29] [Server thread/WARN]:    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
[16:05:29] [Server thread/WARN]:    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[16:05:29] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)
```

**Comment by capnkirok** [comment]
Hmmmmm.... is there a crash? Does is do it after subsequent loadings (server restart/client restart)?

**Comment by Time6628** [comment]
I do not think there is a crash. Also, I am pretty sure it still occurs after both restarts.

**Comment by capnkirok** [comment]
The note above only occurs when first time users to 1.3.8 join. Should not prevent login. Will investigate on the ATLauncher.

**Comment by capnkirok** [comment]
I was able to create a 1.04 Server and new instance of CrainerCraft 1.0.4 using ATLauncher, and was able to login without issue. Also tried upgrading from 1.0.2 to 1.0.4. So, not able to reproduce your error :/. Any more info you can give me? Did you update both client and server in ATLLauncher? Can you paste your whole server log? The above errors would not prevent login, so there is something else (I think).

**Comment by Time6628** [comment]
Sorry for not getting back to you sooner, I had surgery and wasn't able to respond for a while. This issue seems to be resolved as of now though :smile_cat:

**Comment by capnkirok** [comment]
Ah, great news. Happy new year, and hope you are all better now :)
