### ISSUE TITLE
Enchanting Table Pet not opening

### ISSUE THREAD

**Issue by Frobuzmumber** [capnkirok/Inventory-Pets#84]
I am using 1.9 inventory pets (1.4.6 Release) and several other mods, and when I try to open the enchanting table pet, it doesn't open. The server console shows the following error
[spoiler][10:29:54] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: com.inventorypets.petContainerEnchantment.<init>(Lnet/minecraft/entity/player/InventoryPlayer;Lnet/minecraft/world/World;)V
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_91]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_91]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [g.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:664) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:386) [la.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NoSuchMethodError: com.inventorypets.petContainerEnchantment.<init>(Lnet/minecraft/entity/player/InventoryPlayer;Lnet/minecraft/world/World;)V
        at com.inventorypets.ContainerPetEnchantingTable.<init>(ContainerPetEnchantingTable.java:12) ~[ContainerPetEnchantingTable.class:?]
        at com.inventorypets.GuiHandlerInventoryPets.getServerGuiElement(GuiHandlerInventoryPets.java:20) ~[GuiHandlerInventoryPets.class:?]
        at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:244) ~[NetworkRegistry.class:?]
        at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:80) ~[FMLNetworkHandler.class:?]
        at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2462) ~[zj.class:?]
        at com.inventorypets.petEnchantingTable.func_77659_a(petEnchantingTable.java:412) ~[petEnchantingTable.class:?]
        at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:159) ~[adq.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:361) ~[ls.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:712) ~[mb.class:?]
        at net.minecraft.network.play.client.CPacketPlayerBlockPlacement.func_148833_a(SourceFile:32) ~[jh.class:?]
        at net.minecraft.network.play.client.CPacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jh.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_91]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[g.class:?]
        ... 5 more
[/spoiler]

There is no message in the client side.
I do have lapis nuggets in my inventory as well
This is a directory list with all my mods (note the .dis mods are disabled)
[modlist.txt](https://github.com/capnkirok/Inventory-Pets/files/314181/modlist.txt)

I am using forge version 1901

This seems to ONLY happen on the server, not on single player. Config files are identical

**Comment by capnkirok** [comment]
Yep. Good catch. Had a wrong variable in there. Fixed in dev.
