### ISSUE TITLE
petAnvil doesn't work well on SMP

### ISSUE THREAD

**Issue by RyogaK** [capnkirok/Inventory-Pets#89]
I got a following message on SMP server, and incoming player will be disconnected.

```
[22:28:44] [Server thread/WARN]: Failed to handle packet for /[My IP:port]
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:380) ~[ls.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:163) ~[mc.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:193) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) ~[em.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [mb.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:730) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:385) [lb.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
        at com.inventorypets.petAnvil.func_77663_a(petAnvil.java:310) ~[petAnvil.class:?]
        at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:434) ~[adq.class:?]
        at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:340) ~[zi.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:498) ~[zj.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1976) ~[sa.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:227) ~[zj.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303) ~[ls.class:?]
        ... 9 more
```

**Comment by capnkirok** [comment]
Well that's not good. Will check it out.

Update: Just tested with multiple users. Not seeing an issue. What version is your Forge Server? 

The line it references has to do with OreDictionary, which should be fine. Were you doing anything specific at the time of the error, or did it just break?

PC

**Comment by RyogaK** [comment]
Thanks your feedback!

I just tried to login to server, and it happened with only that.
I see, so you meant the line is related eating iron nugget, right? if so, it perhaps is issue that OreDictionary is broken by some conflict between other mods.
I'll investigate more. 😉

**Comment by capnkirok** [comment]
Let me know what other mods you have in your environment if you can, and also if you have time, check to see if it crashes if you use it standalone, just as a test. Thanks!

**Comment by APolarBaer** [comment]
this is happening to me aswell
right when the anvil pet went to eat now i cant get back in to my server 

```

26.06 19:28:24 [Server] INFO net.minecraft.util.ReportedException: Ticking player
26.06 19:28:24 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:380) ~[ls.class:?]
26.06 19:28:24 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:163) ~[mc.class:?]
26.06 19:28:24 [Server] INFO at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:212) ~[NetworkDispatcher$1.class:?]
26.06 19:28:24 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) ~[em.class:?]
26.06 19:28:24 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [mb.class:?]
26.06 19:28:24 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:730) [MinecraftServer.class:?]
26.06 19:28:24 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:385) [lb.class:?]
26.06 19:28:24 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611) [MinecraftServer.class:?]
26.06 19:28:24 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469) [MinecraftServer.class:?]
26.06 19:28:24 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
26.06 19:28:24 [Server] INFO Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
26.06 19:28:24 [Server] INFO at com.inventorypets.petAnvil.func_77663_a(petAnvil.java:310) ~[petAnvil.class:?]
26.06 19:28:24 [Server] INFO at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:435) ~[adq.class:?]
26.06 19:28:24 [Server] INFO at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:340) ~[zi.class:?]
26.06 19:28:24 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:498) ~[zj.class:?]
26.06 19:28:24 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1976) ~[sa.class:?]
26.06 19:28:24 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:227) ~[zj.class:?]
26.06 19:28:24 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303) ~[ls.class:?]
26.06 19:28:24 [Server] INFO ... 9 more
26.06 19:28:24 [Disconnect] User APolarBaer has disconnected, reason: Internal server error
```

my mods
http://pastebin.com/edit/1tFAAqZW
better combat mod also

**Comment by capnkirok** [comment]
Thanks, @APolarBaer, this helps. From the log, it appears to be running some client side code on the server. Let me see how this is happening. I will take a closer look and try to get a patch out in the next day.

**Comment by capnkirok** [comment]
@APolarBaer there's nothing in the pastebin, can you resend?

**Comment by APolarBaer** [comment]
mines 1.9.4 owo 

```
UCHIJA  mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)
UCHIJA  FML{8.0.99.99} [Forge Mod Loader] (forge-1.9.4-12.17.0.1980-1.10.0.jar)
UCHIJA  Forge{12.17.0.1980} [Minecraft Forge] (forge-1.9.4-12.17.0.1980-1.10.0.jar)
UCHIJA  Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.0.7.0.jar)
UCHIJA  OpenComputers|Core{1.6.0.2-beta.3} [OpenComputers (Core)] (minecraft.jar)
UCHIJA  ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.9.4-alpha-1.0.0a.jar)
UCHIJA  JEI{3.6.7.216} [Just Enough Items] (jei_1.9.4-3.6.7.216.jar)
UCHIJA  abyssalcraft{1.9.2.1} [AbyssalCraft] (AbyssalCraft-1.9.4-1.9.2.1.jar)
UCHIJA  acblocks{1.1.0} [AbyssalBlocks] (AbyssalBlocks-1.9.4-1.1.0.jar)
UCHIJA  additionalbanners{1.2.0.17} [Additional Banners] (AdditionalBanners-1.9.4-1.2.0.18.jar)
UCHIJA  armorplus{1.9.4-3.1.1.0} [ArmorPlus] (ArmorPlus1.9.4-3.1.1.0.jar)
UCHIJA  Aroma1997CoreHelper{1.0.7.0} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.0.7.0.jar)
UCHIJA  AromaBackup{1.0.1.1} [AromaBackup] (AromaBackup-1.9.4-1.0.1.1.jar)
UCHIJA  AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.9.4-1.0.1.1.jar)
UCHIJA  basemetals{2.3.2} [Base Metals] (BaseMetals_1.9.4-2.3.2.6.jar)
UCHIJA  Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar)
UCHIJA  BaublesHud{3.0.0} [Baubles-Hud] (BaublesHud-1.9.4-3.0.0.jar)
UCHIJA  baublesstuff{2.0.10} [Baubles Stuff] (baublesstuff-2.0.10.jar)
UCHIJA  BBG{5.0.0} [BetterBedrockGen] (BBG-1.9.4-5.0.0.jar)
UCHIJA  BetterAchievements{0.3.0.26} [Better Achievements] (BetterAchievements-1.9.4-0.3.0.26.jar)
UCHIJA  BiomesOPlenty{4.1.0.2031} [Biomes O' Plenty] (BiomesOPlenty-1.9.4-4.1.0.2031-universal.jar)
UCHIJA  blockdrops{1.0.4} [Block Drops] (BlockDrops-1.9.4-1.0.4.jar)
UCHIJA  BloodMagic{1.9.4-2.0.2-46} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.0.2-46.jar)
UCHIJA  BloodArsenal{1.9.4-2.0.0-5} [Blood Arsenal] (BloodArsenal-1.9.4-2.0.0-5.jar)
UCHIJA  Botania{r1.8-310} [Botania] (Botania-unofficial.r1.8-310.jar)
UCHIJA  cavern{1.0.8} [Cavern] (Cavern_1.9.4-v1.0.8.jar)
UCHIJA  chancecubes{1.9.4-2.1.3.112} [Chance Cubes] (ChanceCubes-1.9.4-2.1.3.112.jar)
UCHIJA  chiselsandbits{10.9} [Chisels & Bits] (chiselsandbits-10.9.jar)
UCHIJA  ChunkAnimator{1.2} [Chunk Animator] (ChunkAnimator-MC1.9.4-1.2.jar)
UCHIJA  origin{9.1.8} [Origin] (Origin-1.9.4-9.1.8.jar)
UCHIJA  compression{1.1.4} [Compression] (Compression-1.9.4-1.1.4.jar)
UCHIJA  cookingforblockheads{3.1.26} [Cooking for Blockheads] (CookingForBlockheads-mc1.9.4-3.1.26.jar)
UCHIJA  cyclopscore{0.6.3} [Cyclops Core] (CyclopsCore-1.9.4-0.6.3.jar)
UCHIJA  ElecCore{1.5.292} [ElecCore] (ElecCore-1.9.4-1.5.292.jar)
UCHIJA  deepresonance{1.2.0beta35} [DeepResonance] (deepresonance-1.9.4-1.2.0beta35.jar)
UCHIJA  shadowmc{3.3.9} [ShadowMC] (ShadowMC-1.9.4-3.3.9.jar)
UCHIJA  DiscordChat{1.2.0} [DiscordChat] (DiscordChat-1.9.4-1.2.0.jar)
UCHIJA  DurabilityShow{3.1.1} [Durability Show] (Durability Show-1.9.4-3.1.1.jar)
UCHIJA  endercore{1.9.4-0.4.0.26-alpha} [EnderCore] (EnderCore-1.9.4-0.4.0.26-alpha.jar)
UCHIJA  endercrop{1.9-1.2-1836} [Ender Crop] (endercrop-1.9.4-1.3.1.jar)
UCHIJA  Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar)
UCHIJA  EnderIO{1.9.4-3.0.0.46_alpha} [Ender IO] (EnderIO-1.9.4-3.0.0.46_alpha.jar)
UCHIJA  EnderZoo{1.9.4-1.2.2.40} [Ender Zoo] (EnderZoo-1.9.4-1.2.2.40.jar)
UCHIJA  ValkyrieLib{1.9.4-0.9.12} [Valkyrie Lib] (valkyrielib-1.9.4-0.9.12.jar)
UCHIJA  EnvironmentalTech{1.9.4-0.9.4d} [Environmental Tech] (environmentaltech-1.9.4-0.9.4d.jar)
UCHIJA  evilcraft{0.10.2} [EvilCraft] (EvilCraft-1.9.4-0.10.2.jar)
UCHIJA  expandablebackpack{1.0} [Expandable Backpacks] (expandableBackpacks1.0.2-1.9.4.jar)
UCHIJA  ExtraBitManipulation{1.9-2.1.2} [Extra Bit Manipulation] (ExtraBitManipulation-1.9.4-2.1.0.jar)
UCHIJA  FortuneOres{3.0.4} [FortuneOres] (FortuneOres-MC1.9.4-3.0.4.jar)
UCHIJA  furnus{1.82} [Furnus] (Furnus-1.9.4-1.82.jar)
UCHIJA  lit{@VERSION@} [Little Insignificant Things] (LittleInsignificantThings-1.9.4-2.0.2.jar)
UCHIJA  SilentLib{1.0.10} [Silent Lib] (SilentLib-1.9.4-1.0.10-18.jar)
UCHIJA  SilentGems{2.0.18} [Silent's Gems] (SilentsGems-1.9.4-2.0.18-47.jar)
UCHIJA  gemulation{1.9.4-3.0.2} [Gemulation] (Gemulation-1.9.4-3.0.2.jar)
UCHIJA  gravelminer{4.0.2} [GravelMiner] (GravelMiner-mc1.9.4-4.0.2.jar)
UCHIJA  gravestone{1.3.0} [Gravestone] (Gravestone Mod 1.3.0.jar)
UCHIJA  Harvest{1.9.4-1.0.1-6} [Harvest] (Harvest-1.9.4-1.0.1-6.jar)
UCHIJA  HelpFixer{1.3.14} [HelpFixer] (HelpFixer-1.9.4-1.3.14.jar)
UCHIJA  InventoryPets{1.4.7.1} [Inventory Pets] (inventorypets-1.9.4-1.4.7.1.jar)
UCHIJA  inventorytweaks{1.61-beta-54-009e843} [Inventory Tweaks] (InventoryTweaks-1.61-beta-54.jar)
UCHIJA  IronChest{6.0.146.788} [Iron Chest] (ironchest-1.9.4-6.0.146.788.jar)
UCHIJA  journeymap{1.9.4-5.2.3} [JourneyMap] (journeymap-1.9.4-5.2.3-unlimited.jar)
UCHIJA  jeresources{0.4.6.39} [Just Enough Resources] (JustEnoughResources-1.9.4-0.4.6.39.jar)
UCHIJA  LunatriusCore{1.1.2.35} [LunatriusCore] (LunatriusCore-1.9.4-1.1.2.35-universal.jar)
UCHIJA  lycanitesmobs{1.14.3.3 - MC 1.9.4} [Lycanites Mobs] (LycanitesMobsComplete 1.14.3.3 [1.9.4].jar)
UCHIJA  arcticmobs{1.14.3.3 - MC 1.9.4} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.14.3.3 [1.9.4].jar)
UCHIJA  demonmobs{1.14.3.3 - MC 1.9.4} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.14.3.3 [1.9.4].jar)
UCHIJA  desertmobs{1.14.3.3 - MC 1.9.4} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.14.3.3 [1.9.4].jar)
UCHIJA  forestmobs{1.14.3.3 - MC 1.9.4} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.14.3.3 [1.9.4].jar)
UCHIJA  freshwatermobs{1.14.3.3 - MC 1.9.4} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.14.3.3 [1.9.4].jar)
UCHIJA  infernomobs{1.14.3.3 - MC 1.9.4} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.14.3.3 [1.9.4].jar)
UCHIJA  junglemobs{1.14.3.3 - MC 1.9.4} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.14.3.3 [1.9.4].jar)
UCHIJA  mountainmobs{1.14.3.3 - MC 1.9.4} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.14.3.3 [1.9.4].jar)
UCHIJA  plainsmobs{1.14.3.3 - MC 1.9.4} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.14.3.3 [1.9.4].jar)
UCHIJA  saltwatermobs{1.14.3.3 - MC 1.9.4} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.14.3.3 [1.9.4].jar)
UCHIJA  shadowmobs{1.14.3.3 - MC 1.9.4} [Lycanites Shadow Mobs] (LycanitesMobsComplete 1.14.3.3 [1.9.4].jar)
UCHIJA  swampmobs{1.14.3.3 - MC 1.9.4} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.14.3.3 [1.9.4].jar)
UCHIJA  mantle{1.9.4-0.10.2.jenkins149} [Mantle] (Mantle-1.9.4-0.10.2.jar)
UCHIJA  am{1.5.5} [Marines Armor and Weapons] (Marines Armor and Weapons 1.9.4.jar)
UCHIJA  testdummy{1.10} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.11.jar)
UCHIJA  modifiable_armor{2.0.2} [Modifiable Armor 2] (ModifiableArmor2-1.9.4-2.0.2.jar)
UCHIJA  Morpheus{1.9.4-3.1.5} [Morpheus] (Morpheus-1.9.4-3.1.5.jar)
UCHIJA  MouseTweaks{2.6.3} [Mouse Tweaks] (MouseTweaks-2.6.3-mc1.9.4.jar)
UCHIJA  AS_MultiMine{1.5.3} [Multi Mine] (MultiMine-1.9.4.jar)
UCHIJA  Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.2-9.jar)
UCHIJA  netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9.4-4.0.1.jar)
UCHIJA  recipehandler{0.4} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.4(1.9).jar)
UCHIJA  OpenComputers{1.6.0.2-beta.3} [OpenComputers] (OpenComputers-MC1.9.4-1.6.0.2-beta.3.jar)
UCHIJA  orespawn{1.0.3} [Ore Spawn] (OreSpawn_1.9.4-1.0.3.jar)
UCHIJA  harvestcraft{1.9.4-pre} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4c.jar)
UCHIJA  parachutemod{1.4.3} [Parachute Mod] (parachutemod-ng-1.9.4-1.4.3-403.jar)
UCHIJA  placemod{3.4} [Placemod] (placemod-3.4-1.9.4.jar)
UCHIJA  playerstats{1.1.1} [Player Stats] (PlayerStats_1.9.4-1.1.1.jar)
UCHIJA  progressiveautomation{1.6.46} [Progressive Automation] (ProgressiveAutomation-1.9.4-1.6.46.jar)
UCHIJA  Psi{r1.0-35} [Psi] (Psi-r1.0-35.jar)
UCHIJA  randomthings{3.7.3} [Random Things] (RandomThings-MC1.9.4-3.7.3.jar)
UCHIJA  xreliquary{1.9.4-1.3.2.390} [Reliquary] (Reliquary-1.9.4-1.3.2.390.jar)
UCHIJA  rftools{4.66} [RFTools] (rftools-1.9.4-4.66.jar)
UCHIJA  rftoolsdim{4.30beta43} [RFTools Dimensions] (rftoolsdim-1.9.4-4.30beta43.jar)
UCHIJA  Roguelike{1.5.3} [Roguelike Dungeons] (RoguelikeDungeons-1.9.4-1.5.3.jar)
UCHIJA  roots{0.1} [Roots] (roots-0.005.jar)
UCHIJA  SGExtraParts{1.0.3} [Silent's Gems: Extra Parts] (SGExtraParts-1.9.4-1.0.3-4.jar)
UCHIJA  SimpleDimensions{1.3} [Simple Dimensions] (SimpleDimensions-MC1.9.4-1.3.jar)
UCHIJA  flammpfeil.slashblade{mc1.9.4-r11} [SlashBlade] (SlashBlade-mc1.9.4-r11.jar)
UCHIJA  Stackie{1.6.0.42} [Stackie] (Stackie-1.9.4-1.6.0.42-universal.jar)
UCHIJA  storagenetwork{1.12.0} [Storage Network] (StorageNetwork-1.9.4-1.12.0.jar)
UCHIJA  tconstruct{1.9.4-2.3.3.jenkins263} [Tinkers' Construct] (TConstruct-1.9.4-2.3.3.jar)
UCHIJA  teamup{1.0.0} [TeamUp] (TeamUp-1.1.0-1.9.4.jar)
UCHIJA  terrainCrystals{1.0.8} [Terrain Crystals] (Terrain Crystals - 1.9.4 - 1.0.8.jar)
UCHIJA  Tesla{1.1.0.24} [TESLA] (Tesla-1.9.4-1.1.0.24.jar)
UCHIJA  TODOList{1.0.8} [TODO List] (TODOList-1.0.8.jar)
UCHIJA  torcharrowsmod{1.9.4-2} [TorchArrowsMod] (torcharrows-1.9.4-2.jar)
UCHIJA  torohealthmod{1.9.4-5} [ToroHealth Damage Indicators] (torohealth-1.9.4-5.jar)
UCHIJA  CaveCraft{@VERSION@} [TSON Craft] (TSON Craft 2.8.0 - 1.9.4.jar)
UCHIJA  AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.9.4.jar)
UCHIJA  WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.9-1.1.7.jar)
UCHIJA  warpscrolls{1.0} [warpscrolls] (Warp Scrolls 1.9.4 1.0.2.jar)
UCHIJA  ICSE{1.0.0.0} [I Can See Everything] (Wawla-1.9.4-2.2.1.190.jar)
UCHIJA  wawla{2.2.1.188} [What Are We Looking At] (Wawla-1.9.4-2.2.1.190.jar)
UCHIJA  Woot{1.9.4-0.3.0-beta} [Woot] (woot-1.9.4-0.3.0-beta.jar)
UCHIJA  ZDoctorBB{1.1} [Blood Baubles] (ZDoctorBB-1.1.jar)
```

**Comment by APolarBaer** [comment]
Any news owo love the pets and really could use this one x3

**Comment by capnkirok** [comment]
Still looking into it. Wasn't what I thought it was, so I need to do a conflict check....

**Comment by APolarBaer** [comment]
Okay~

**Comment by capnkirok** [comment]
Ok, I got it. Will roll out a fix today. Only on 1.9, 1.9.4, and 1.10. Evidently, you cannot access the following from the server: inventory.armorItemInSlot();

Went back to the original method.

**Comment by APolarBaer** [comment]
Weeeew
